projects:
  server:
    schema: packages/api/schema.gql
  web-client:
    schema: packages/api/schema.gql
    documents:
      - packages/client/src/**/*.graphql.ts
  api-client:
    schema: packages/api/schema.gql
    documents:
      - packages/api-client/src/**/*.ts
