yarnPath: .yarn/releases/yarn-3.2.0.cjs
nodeLinker: node-modules
logFilters:
  # There's a bunch of YN0002 errors from these packages having inaccurate peerDependencies
  - pattern: "@(parcel/|storybook/|endemolshinegroup/|sb@)* doesn't provide"
    level: discard