# Hide peer dependency errors from these packages, they're fake news
logFilters:
  - level: discard
    pattern: "@(parcel/|storybook/|endemolshinegroup/|sb@)* doesn't provide"
# I don't want to deal with pnp yet
nodeLinker: node-modules

plugins:
  # Adds yarn upgrade-interactive
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
